
function love.conf(t)
    t.identity = "TS2D"                 -- The name of the save directory (string)
    t.appendidentity = false            -- Search files in source directory before save directory (boolean)
    --t.version = "11.5"                  -- The LÖVE version this game was made for (string)
    t.console = false                   -- Attach a console (boolean, Windows only)
    --t.accelerometerjoystick = true      -- Enable the accelerometer on iOS and Android by exposing it as a Joystick (boolean)
    --t.externalstorage = false           -- True to save files (and read from the save directory) in external storage on Android (boolean) 
    --t.highdpi = false                   -- Enable high-dpi mode for the window on a Retina display (boolean)

    --t.audio.mic = false                 -- Request and use microphone capabilities in Android (boolean)
    --t.audio.mixwithsystem = true        -- Keep background music playing when opening LOVE (boolean, iOS and Android only)

    --t.window.gammacorrect = false       -- Enable gamma-correct rendering, when supported by the system (boolean)
    t.window.title = "Tactical Strike 2D" -- The window title (string)
    t.window.icon = "cs2d.png"          -- Filepath to an image to use as the window's icon (string)
    t.window.width = 800                -- The window width (number)
    t.window.height = 600               -- The window height (number)
    --t.window.width = 1280                -- The window width (number)
    --t.window.height = 728               -- The window height (number)
    t.window.borderless = false         -- Remove all border visuals from the window (boolean)
    t.window.resizable = false          -- Let the window be user-resizable (boolean)
    --t.window.minwidth = 1               -- Minimum window width if the window is resizable (number)
    --t.window.minheight = 1              -- Minimum window height if the window is resizable (number)
    t.window.fullscreen = false         -- Enable fullscreen (boolean)
    t.window.fullscreentype = "desktop" -- Choose between "desktop" fullscreen or "exclusive" fullscreen mode (string)
    t.window.vsync = 0                  -- Vertical sync mode (number)
    t.window.msaa = 0                   -- The number of samples to use with multi-sampled antialiasing (number)

end
