local enum = {}
enum.TILE_PROPERTY = {
	[0]="normal floor without sound";
	[1]="wall";
	[2]="obstacle";
	[3]="wall without shadow";
	[4]="obstacle without shadow";
	[5]="wall that is rendered at floor level";
	[10]="floor dirt";
	[11]="floor snow (with footprints and fx)";
	[12]="floor step";
	[13]="floor tile";
	[14]="floor wade (water with wave fx)";
	[15]="floor metal";
	[16]="floor wood";
	[50]="deadly normal";
	[51]="deadly toxic";
	[52]="deadly explosion";
	[53]="deadly abyss";
}

enum.EFFECT_LIST = {
	"sparkle",
	"fire",
}

enum.DEFAULT_MOD = {
	brightness = 100,
	rotation = 0,
	color = {
		red = 255,
		blue = 255,
		green = 255,
	},
	modifier = 0,
	blending = 0,
}



enum.ENTITY_TYPE = {
	["null"] = {
		name = "Null";
		color = {1,1,1};
	};
	[0] = {
		name = "Info_T";
		color = {1,0,0};
		label = "T";
	};
	[1] = { 
		name = "Info_CT";
		color = {0,0,1};
		label = "CT";
	};
	[21] = {
		name ="Env_Item";
		color = {0,1,0};
		label = "Item";
	};
	[22] = {
		name ="Env_Sprite";
		color = {0,1,0};
		label = "Spr";
	};
	[23]={
		name ="Env_Sound";
		color = {0,1,0};
		label = "Sound";
	};
	[24]={
		name ="Env_Decal";
		color = {0,1,0};
		label = "Decal";
	};
	[25]={
		name ="Env_Breakable";
		color = {0,1,0};
		label = "Spr";
	};
	[26]={
		name ="Env_Explode";
		color = {0,1,0};
		label = "Explode";
	};
	[27]={
		name ="Env_Hurt";
		color = {0,1,0};
		label = "Hurt";
	};
	[28]={
		name ="Env_Image";
		color = {0,1,0};
		label = "Image";
	};
	[29]={
		name ="Env_Object";
		color = {0,1,0};
		label = "Object";
	};
	[30]={
		name ="Env_Building";
		color = {0,1,0};
		label = "Build";
	};
	[31]={
		name ="Env_NPC";
		color = {0,1,0};
		label = "NPC";
	};
	[32]={
		name ="Env_Room";
		color = {0,1,0};
		label = "Room";
	};
	[33]={
		name ="Env_Light";
		color = {0,1,0};
		label = "Light";
	};
	[34]={
		name ="Env_LightStripe";
		color = {0,1,0};
		label = "LStripe";
	};
	[35]={
		name ="Env_Cube3D";
		color = {0,1,0};
		label = "C3D";
	};
}

enum.TILE_BLEND_DIR = {
	[-1] = {0, 0};
	[0] = { 0,-1};
	[1] = { 1,-1};
	[2] = { 1, 0};
	[3] = { 1, 1};
	[4] = { 0, 1};
	[5] = {-1, 1};
	[6] = {-1, 0};
	[7] = {-1,-1};
}

enum.TILE_MODE_HEIGHT = {
	[0]=0.0,		-- 0  normal floor without sound
	[1]=1.0,	-- 1  wall
	[2]=0.5,	-- 2  obstacle
	[3]=1.0,	-- 3  wall without shadow
	[4]=0.5,	-- 4  obstacle without shadow
	[5]=0.0,		-- 5  wall that is rendered at floor level
	[10]=0.0,		-- 10 floor dirt
	[11]=0.0,		-- 11 floor snow (with footprints and fx)
	[12]=0.0,		-- 12 floor step
	[13]=0.0,		-- 13 floor tile
	[14]=0.0,		-- 14 floor wade (water with wave fx)
	[15]=0.0,		-- 15 floor metal
	[16]=0.0,		-- 16 floor wood
	[50]=0.0,		-- 50 deadly normal
	[51]=0.0,		-- 51 deadly toxic
	[52]=0.0,		-- 52 deadly explosion
	[53]=0.0,		-- 53 deadly abyss
}

enum.entity_type={
	[0]="Info_T",
	[1]="Info_CT",
	[2]="Info_VIP",
	[3]="Info_Hostage",
	[4]="Info_RescuePoint",
	[5]="Info_BombSpot",
	[6]="Info_EscapePoint",
	[7]="Info_Target",
	[8]="Info_Animation",
	[9]="Info_Storm",
	[10]="Info_TileFX",
	[11]="Info_NoBuying",
	[12]="Info_NoWeapons",
	[13]="Info_NoFOW",
	[14]="Info_Quake",
	[15]="Info_CTF_Flag",
	[16]="Info_OldRender",
	[17]="Info_Dom_Point",
	[18]="Info_NoBuildings",
	[19]="Info_BotNode",
	[20]="Info_TeamGate",
	[21]="Env_Item",
	[22]="Env_Sprite",
	[23]="Env_Sound",
	[24]="Env_Decal",
	[25]="Env_Breakable",
	[26]="Env_Explode",
	[27]="Env_Hurt",
	[28]="Env_Image",
	[29]="Env_Object",
	[30]="Env_Building",
	[31]="Env_NPC",
	[32]="Env_Room",
	[33]="Env_Light",
	[34]="Env_LightStripe",
	[35]="Env_Cube3D",
	[50]="Gen_Particles",
	[51]="Gen_Sprites",
	[52]="Gen_Weather",
	[53]="Gen_FX",
	[70]="Func_Teleport",
	[71]="Func_DynWall",
	[72]="Func_Message",
	[73]="Func_GameAction",
	[80]="Info_NoWeather",
	[81]="Info_RadarIcon",
	[90]="Trigger_Start",
	[91]="Trigger_Move",
	[92]="Trigger_Hit",
	[93]="Trigger_Use",
	[94]="Trigger_Delay",
	[95]="Trigger_Once",
	[96]="Trigger_If"
}

enum.itemname = {
	["USP"]=1;
	["GLOCK"]=2;
	["DEAGLE"]=3;
	["P228"]=4;
	["ELITE"]=5;
	["FIVE-SEVEN"]=6;
	["M3"]=10;
	["XM1014"]=11;
	["MP5"]=20;
	["TMP"]=21;
	["P90"]=22;
	["MAC 10"]=23;
	["UMP45"]=24;
	["AK-47"]=30;
	["SG552"]=31;
	["M4A1"]=32;
	["AUG"]=33;
	["SCOUT"]=34;
	["AWP"]=35;
	["G3SG1"]=36;
	["SG550"]=37;
	["GALIL"]=38;
	["FAMAS"]=39;
	["M249"]=40;
	["TACTICAL SHIELD"]=41;
	["SHIELD"]=41;
	["LASER"]=45;
	["FLAMETHROWER"]=46;
	["RPG LAUNCHER"]=47;
	["ROCKET LAUNCHER"]=48;
	["GRENADE LAUNCHER"]=49;
	["HE"]=51;
	["FLASHBANG"]=52;
	["SMOKE GRENADE"]=53;
	["SMOKE"]=53;
	["FLARE"]=54;
	["DEFUSE KIT"]=56;
	["KEVLAR"]=57;
	["KEVLAR+HELM"]=58;
	["NIGHT VISION"]=59;
	["GAS MASK"]=60;
	["PRIMARY AMMO"]=61;
	["SECONDARY AMMO"]=62;
	["MEDIKIT"]=64;
	["BANDAGE"]=65;
	["COINS"]=66;
	["MONEY"]=67;
	["GOLD"]=68;
	["MACHETE"]=69;
	["GAS GRENADE"]=72;
	["GAS"]=72;
	["MOLOTOV COCKTAIL"]=73;
	["MOLOTOV"]=73;
	["WRENCH"]=74;
	["SNOWBALL"]=75;
	["AIR STRIKE"]=76;
	["MINE"]=77;
	["CLAW"]=78;
	["LIGHT ARMOR"]=79;
	["ARMOR"]=80;
	["HEAVY ARMOR"]=81;
	["MEDIC ARMOR"]=82;
	["SUPER ARMOR"]=83;
	["STEALTH SUIT"]=84;
	["STEALTH ARMOR"]=84;
	["STEALTH"]=84;
	["CHAINSAW"]=85;
	["GUT BOMB"]=86;
	["LASER MINE"]=87;
	["PORTAL GUN"]=88;
	["PORTAL"]=88;
	["SATCHEL CHARGE"]=89;
	["SATCHEL"]=89;
	["M134"]=90;
	["FN F2000"]=91;
	["TESLA"]=92;
}

---@class Item
---@field name string
---@field alt_name string
---@field internal_name string
---@field category string
---@field damage number
---@field price number
---@field ammo_cap number
---@field ammo_mag number
---@field rate_of_fire number
---@field range number
---@field weight number
---@field accuracy number
---@field common_path string
---@field dropped_image string
---@field display_image string
---@field kill_image string
---@field held_image string
---@field player_stance string
---@field acessory table
---@field offset number
enum.itemlist = {
	[1] = {
		name = "USP", -- Display name
		alt_name = "Heckler & Koch USP", -- Name gotten from external source (wikipedia, etc)
		internal_name = "usp", -- Name used internally by code
		category = "secondary", -- Category (primary, secondary, melee, armor, throwable, other [example of other: flag, bomb, medikit] )
		price = 500, -- Value in shop menu
		damage = 24, -- Damage
		ammo_cap = 100, -- Reserve ammo 
		ammo_mag = 12, -- Ammo in magazine
		rate_of_fire = 9, -- Frame delay 
		range = 300, -- Range in pixels  -[[(afair this range is multipled by formula * 3, so pixels is 900, 300 is value)]]
		weight = 900, -- real-life weight of this weapon, gotten from wikipedia or something
		accuracy = 100,  -- Accuracy in percentage (100% = perfect, decreases by 10% for every point in https://www.cs2d.com/weapons.php)
		common_path = "gfx/weapons/", -- Weapon image source directory
		dropped_image = "usp_d.bmp", -- Dropped image
		held_image = "usp.bmp", -- Held (in hand or worn) image
		display_image = "usp_m.bmp", -- Image that appears when buying
		kill_image = "usp_k.bmp", -- Small icon that appears on the kill log on the top right corner
		player_stance = "handgun", -- Which player sprite should appear when holding/wearing this item (stances: handgun, rifle, melee, object, armor, zombie, nothing)
		acessory = {
			silencer_image = "usp_silenced.bmp",
		};
	};
	[2] = {
		name = "GLOCK",
		alt_name = "Glock 18",
		internal_name = "glock",
		category = "secondary",
		price = 400,
		damage = 21,
		ammo_cap = 120,
		ammo_mag = 20,
		rate_of_fire = 9,
		range = 250,
		weight = 620,
		accuracy = 100,
		common_path = "gfx/weapons/",
		dropped_image = "glock_d.bmp",
		held_image = "glock.bmp",
		display_image = "glock_m.bmp",
		kill_image = "glock_k.bmp",
		player_stance = "handgun",
	};
	[3] = {
		name = "DEAGLE",
		alt_name = "Desert Eagle",
		internal_name = "deagle",
		category = "secondary",
		price = 650,
		damage = 34,
		ammo_cap = 35,
		ammo_mag = 7,
		rate_of_fire = 15,
		range = 300,
		weight = 2000,
		accuracy = 100,
		common_path = "gfx/weapons/",
		dropped_image = "deagle_d.bmp",
		held_image = "deagle.bmp",
		display_image = "deagle_m.bmp",
		kill_image = "deagle_k.bmp",
		player_stance = "handgun",
	};
	[4] = {
		name = "P228",
		alt_name = "SIG Sauer P228",
		internal_name = "p228",
		category = "secondary",
		price = 600,
		damage = 22,
		ammo_cap = 53,
		ammo_mag = 13,
		rate_of_fire = 9,
		range = 300,
		weight = 850,
		accuracy = 100,
		common_path = "gfx/weapons/",
		dropped_image = "p228_d.bmp",
		held_image = "p228.bmp",
		display_image = "p228_m.bmp",
		kill_image = "p228_k.bmp",
		player_stance = "handgun",
	};	
	[5] = {
		name = "ELITE",
		alt_name = "Elite Guardian Tactical Sidearm",
		internal_name = "elite",
		category = "secondary",
		price = 1000,
		damage = 22,
		ammo_cap = 120,
		ammo_mag = 15,
		rate_of_fire = 8,
		range = 300,
		weight = 820,
		accuracy = 100,
		common_path = "gfx/weapons/",
		dropped_image = "elite_d.bmp",
		held_image = "elite.bmp",
		display_image = "elite_m.bmp",
		kill_image = "elite_k.bmp",
		player_stance = "handgun",
	};	
	[6] = {
		name = "FIVE-SEVEN",
		alt_name = "FN Herstal Five-Seven",
		internal_name = "fiveseven",
		category = "secondary",
		price = 750,
		damage = 21,
		ammo_cap = 100,
		ammo_mag = 20,
		rate_of_fire = 7,
		range = 300,
		weight = 590,
		accuracy = 100,
		common_path = "gfx/weapons/",
		dropped_image = "fiveseven_d.bmp",
		held_image = "fiveseven.bmp",
		display_image = "fiveseven_m.bmp",
		kill_image = "fiveseven_k.bmp",
		player_stance = "handgun",
	};
	[10] = {
		name = "M3",
		alt_name = "M3 Grease Gun",
		internal_name = "m3",
		category = "primary",
		price = 1700,
		damage = 26,
		ammo_cap = 32,
		ammo_mag = 8,
		rate_of_fire = 20,
		range = 50,
		weight = 3900,
		accuracy = 0,  --https://www.cs2d.com/weapons.php accuracy: 10. 100% - (10 * 10%) = 0 
		common_path = "gfx/weapons/",
		dropped_image = "m3_d.bmp",
		held_image = "m3.bmp",
		kill_image = "m3_k.bmp",
		display_image = "m3_m.bmp", 
		player_stance = "rifle",
	};
	[11] = {
		name = "XM1014",
		alt_name = "Benelli XM1014",
		internal_name = "xm1014",
		category = "primary",
		price = 3000,
		damage = 22,
		ammo_cap = 32,
		ammo_mag = 7,
		rate_of_fire = 12,
		range = 50,
		weight = 3400,
		accuracy = 0,  --https://www.cs2d.com/weapons.php accuracy: 10. 100% - (10 * 10%) = 0 
		common_path = "gfx/weapons/",
		dropped_image = "xm1014_d.bmp",
		held_image = "xm1014.bmp",
		kill_image = "xm1014_k.bmp",
		display_image = "xm1014_m.bmp", 
		player_stance = "rifle",
	};
	[20] = {
		name = "MP5",
		alt_name = "Heckler & Koch Maschinenpistole 5",
		internal_name = "mp5",
		category = "primary",
		price = 1500,
		damage = 13,
		ammo_cap = 120,
		ammo_mag = 30,
		rate_of_fire = 3,
		range = 300,
		weight = 2500,
		accuracy = 80, 
		common_path = "gfx/weapons/",
		dropped_image = "mp5_d.bmp",
		held_image = "mp5.bmp",
		kill_image = "mp5_k.bmp",
		display_image = "mp5_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[21] = {
		name = "TMP",
		alt_name = "Steyr Mannlicher Tactical Machine Pistol",
		internal_name = "tmp",
		category = "primary",
		price = 1250,
		damage = 9,
		ammo_cap = 120,
		ammo_mag = 30,
		rate_of_fire = 2,
		range = 100,
		weight = 1300,
		accuracy = 60, 
		common_path = "gfx/weapons/",
		dropped_image = "tmp_d.bmp",
		held_image = "tmp.bmp",
		kill_image = "tmp_k.bmp",
		display_image = "tmp_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[22] = {
		name = "P90",
		alt_name = "FN Herstal P90",
		internal_name = "p90",
		category = "primary",
		price = 2350,
		damage = 11,
		ammo_cap = 100,
		ammo_mag = 50,
		rate_of_fire = 2,
		range = 300,
		weight = 2000,
		accuracy = 70, 
		common_path = "gfx/weapons/",
		dropped_image = "p90_d.bmp",
		held_image = "p90.bmp",
		kill_image = "p90_k.bmp",
		display_image = "p90_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[23] = {
		name = "Mac 10",
		alt_name = "Gordon Ingram Military Armament Corporation Model 10",
		internal_name = "mac10",
		category = "primary",
		price = 1400,
		damage = 9,
		ammo_cap = 90,
		ammo_mag = 30,
		rate_of_fire = 2,
		range = 100,
		weight = 1600,
		accuracy = 60, 
		common_path = "gfx/weapons/",
		dropped_image = "mac10_d.bmp",
		held_image = "mac10.bmp",
		kill_image = "mac10_k.bmp",
		display_image = "mac10_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[24] = {
		name = "UMP45",
		alt_name = "Heckler & Koch Universal Machine Pistol",
		internal_name = "ump45",
		category = "primary",
		price = 1700,
		damage = 15,
		ammo_cap = 90,
		ammo_mag = 25,
		rate_of_fire = 4,
		range = 300,
		weight = 2800,
		accuracy = 70, 
		common_path = "gfx/weapons/",
		dropped_image = "ump45_d.bmp",
		held_image = "ump45.bmp",
		kill_image = "ump45_k.bmp",
		display_image = "ump45_m.bmp",
		player_stance = "rifle",
		acessory = {};
	};
	[30] = {
		name = "AK-47",
		alt_name = "Avtomat Kalashnikova 1947",
		internal_name = "ak47",
		category = "primary",
		price = 2500,
		damage = 22,
		ammo_cap = 90,
		ammo_mag = 30,
		rate_of_fire = 3,
		range = 300,
		weight = 3470,
		accuracy = 70, 
		common_path = "gfx/weapons/",
		dropped_image = "ak47_d.bmp",
		held_image = "ak47.bmp",
		kill_image = "ak47_k.bmp",
		display_image = "ak47_m.bmp",
		player_stance = "rifle",
		acessory = {};
	};
	[31] = {
		name = "SG552",
		alt_name = "SIG SG 552",
		internal_name = "sg552",
		category = "primary",
		price = 3500,
		damage = 24,
		damage_z1 = 35,
		ammo_cap = 90,
		ammo_mag = 30,
		rate_of_fire = 4,
		range = 350,
		weight = 3500,
		accuracy = 100, 
		common_path = "gfx/weapons/",
		dropped_image = "sg552_d.bmp",
		held_image = "sg552.bmp",
		kill_image = "sg552_k.bmp",
		display_image = "sg552_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[32] = {
		name = "M4A1",
		alt_name = "M4A1 Carbine",
		internal_name = "m4a1",
		category = "primary",
		price = 3100,
		damage = 22,
		ammo_cap = 90,
		ammo_mag = 30,
		rate_of_fire = 3,
		range = 300,
		weight = 3520,
		accuracy = 80, 
		common_path = "gfx/weapons/",
		dropped_image = "m4a1_d.bmp",
		held_image = "m4a1.bmp",
		display_image = "m4a1_m.bmp", 
		kill_image = "m4a1_k.bmp",
		player_stance = "rifle",
		acessory = {
			silencer_image = "m4a1_silenced.bmp",
		};
	};
	[33] = {
		name = "AUG",
		alt_name = "Steyr Mannlicher AUG",
		internal_name = "aug",
		category = "primary",
		price = 3500,
		damage = 24,
		damage_z1 = 35,
		ammo_cap = 90,
		ammo_mag = 30,
		rate_of_fire = 4,
		range = 350,
		weight = 3700,
		accuracy = 100, 
		common_path = "gfx/weapons/",
		dropped_image = "aug_d.bmp",
		held_image = "aug.bmp",
		kill_image = "aug_k.bmp",
		display_image = "aug_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[34] = {
		name = "SCOUT",
		alt_name = "Steyr Mannlicher AUG",
		internal_name = "scout",
		category = "primary",
		price = 2750,
		damage = 45,
		damage_z1 = 50,
		damage_z2 = 100,
		ammo_cap = 60,
		ammo_mag = 10,
		rate_of_fire = 20,
		range = 350,
		weight = 2700,
		accuracy = 100, 
		common_path = "gfx/weapons/",
		dropped_image = "scout_d.bmp",
		held_image = "scout.bmp",
		kill_image = "scout_k.bmp",
		display_image = "scout_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[35] = {
		name = "AWP",
		alt_name = "Arctic Warfare Police",
		internal_name = "awp",
		category = "primary",
		price = 4750,
		damage = 50,
		damage_z1 = 65,
		damage_z2 = 150,
		ammo_cap = 30,
		ammo_mag = 10,
		rate_of_fire = 65,
		range = 400,
		weight = 5500,
		accuracy = 100, 
		common_path = "gfx/weapons/",
		dropped_image = "awp_d.bmp",
		held_image = "awp.bmp",
		kill_image = "awp_k.bmp",
		display_image = "awp_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[36] = {
		name = "G3SG1",
		alt_name = "Heckler & Koch G3SG1",
		internal_name = "g3sg1",
		category = "primary",
		price = 5000,
		damage = 32,
		damage_z1 = 37,
		damage_z2 = 45,
		ammo_cap = 60,
		ammo_mag = 20,
		rate_of_fire = 6,
		range = 350,
		weight = 4500,
		accuracy = 100, 
		common_path = "gfx/weapons/",
		dropped_image = "g3sg1_d.bmp",
		held_image = "g3sg1.bmp",
		kill_image = "g3sg1_k.bmp",
		display_image = "g3sg1_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[37] = {
		name = "SG550",
		alt_name = "SIG SG 550",
		internal_name = "sg550",
		category = "primary",
		price = 4200,
		damage = 30,
		damage_z1 = 35,
		damage_z2 = 40,
		ammo_cap = 90,
		ammo_mag = 30,
		rate_of_fire = 6,
		range = 350,
		weight = 4200,
		accuracy = 100, 
		common_path = "gfx/weapons/",
		dropped_image = "sg550_d.bmp",
		held_image = "sg550.bmp",
		kill_image = "sg550_k.bmp",
		display_image = "sg550_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[38] = {
		name = "GALIL",
		alt_name = "Yisrael Galil",
		internal_name = "galil",
		category = "primary",
		price = 2000,
		damage = 13,
		ammo_cap = 90,
		ammo_mag = 35,
		rate_of_fire = 3,
		range = 300,
		weight = 3500,
		accuracy = 90, 
		common_path = "gfx/weapons/",
		dropped_image = "galil_d.bmp",
		held_image = "galil.bmp",
		kill_image = "galil_k.bmp",
		display_image = "galil_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[39] = {
		name = "FAMAS",
		alt_name = "FAMAS",
		internal_name = "famas",
		category = "primary",
		price = 2250,
		damage = 14,
		ammo_cap = 90,
		ammo_mag = 25,
		rate_of_fire = 3,
		range = 300,
		weight = 3600,
		accuracy = 90, 
		common_path = "gfx/weapons/",
		dropped_image = "famas_d.bmp",
		held_image = "famas.bmp",
		kill_image = "famas_k.bmp",
		display_image = "famas_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[40] = {
		name = "M249",
		alt_name = "SAW M249",
		internal_name = "m249",
		category = "primary",
		price = 5750,
		damage = 15,
		ammo_cap = 200,
		ammo_mag = 100,
		rate_of_fire = 2,
		range = 300,
		weight = 7720,
		accuracy = 20, 
		common_path = "gfx/weapons/",
		dropped_image = "m249_d.bmp",
		held_image = "m249.bmp",
		kill_image = "m249_k.bmp",
		display_image = "m249_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[41] = {
		name = "TACTICAL SHIELD",
		alt_name = "Tactical Shield",
		internal_name = "tacticalshield",
		category = "primary",
		price = 1000,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 3900,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "tacticalshield_d.bmp",
		held_image = "tacticalshield.bmp",
		kill_image = "",
		display_image = "",
		player_stance = "rifle",
		acessory = {};
	};
	[45] = {
		name = "LASER",
		alt_name = "LASER",
		internal_name = "laser",
		category = "primary",
		price = 6500,
		damage = 1000,
		ammo_cap = 45,
		ammo_mag = 15,
		rate_of_fire = 30,
		range = 1000,
		weight = 4300,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "laser_d.bmp",
		held_image = "laser.bmp",
		kill_image = "laser_k.bmp",
		display_image = "laser_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[46] = {
		name = "FLAMETHROWER",
		alt_name = "FLAMETHROWER",
		internal_name = "flamethrower",
		category = "primary",
		price = 3200,
		damage = 30,
		ammo_cap = 200,
		ammo_mag = 100,
		rate_of_fire = 3,
		range = 1000,
		weight = 3000,
		accuracy = 0,
		offset = -20,
		common_path = "gfx/weapons/",
		dropped_image = "flamethrower_d.bmp",
		held_image = "flamethrower.bmp",
		kill_image = "flamethrower_k.bmp",
		display_image = "flamethrower_m.bmp",
		player_stance = "rifle",
		acessory = {};
	};
	[47] = {
		name = "RPG LAUNCHER",
		alt_name = "RPG LAUNCHER",
		internal_name = "rpglauncher",
		category = "primary",
		price = 4000,
		damage = 325,
		ammo_cap = 2,
		ammo_mag = 1,
		rate_of_fire = 50,
		range = 700,
		weight = 3000,
		accuracy = 0,
		offset = -20,
		common_path = "gfx/weapons/",
		dropped_image = "rpglauncher_d.bmp",
		held_image = "rpglauncher.bmp",
		kill_image = "rpglauncher_k.bmp",
		display_image = "rpglauncher_m.bmp",
		player_stance = "rifle",
		acessory = {};
	};
	[48] = {
		name = "ROCKET LAUNCHER",
		alt_name = "ROCKET LAUNCHER",
		internal_name = "rocketlauncher",
		category = "primary",
		price = 5500,
		damage = 70,
		ammo_cap = 60,
		ammo_mag = 20,
		rate_of_fire = 20,
		range = 700,
		weight = 3000,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "rocketlauncher_d.bmp",
		held_image = "rocketlauncher.bmp",
		kill_image = "rocketlauncher_k.bmp",
		display_image = "rocketlauncher_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[49] = {
		name = "GRENADE LAUNCHER",
		alt_name = "GRENADE LAUNCHER",
		internal_name = "grenadelauncher",
		category = "primary",
		price = 5500,
		damage = 75,
		ammo_cap = 60,
		ammo_mag = 20,
		rate_of_fire = 20,
		range = 320,
		weight = 3000,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "grenadelauncher_d.bmp",
		held_image = "grenadelauncher.bmp",
		kill_image = "grenadelauncher_k.bmp",
		display_image = "grenadelauncher_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[50] = {
		name = "KNIFE",
		alt_name = "Knife",
		internal_name = "knife",
		category = "melee",
		price = 0,
		damage = 45,
		damage_z1 = 90,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 8,
		range = 7,
		weight = 150,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "knife.bmp",
		held_image = "knife.bmp",
		kill_image = "knife_k.bmp",
		display_image = "knife.bmp", 
		player_stance = "melee",
		acessory = {};
	};
	[51] = {
		name = "HE",
		alt_name = "High-Explosion Grenade",
		internal_name = "he",
		category = "throwable",
		price = 300,
		damage = 105,
		ammo_cap = 0,
		ammo_mag = 1,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "he.bmp",
		held_image = "he.bmp",
		kill_image = "he_k.bmp",
		display_image = "he_m.bmp", 
		player_stance = "object",
		acessory = {};
	};
	[52] = {
		name = "FLASHBANG",
		alt_name = "Flashbang Grenade",
		internal_name = "flashbang",
		category = "throwable",
		price = 200,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 2,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "flashbang_bmp",
		held_image = "flashbang.bmp",
		kill_image = "flashbang.bmp",
		display_image = "flashbang_m.bmp", 
		player_stance = "object",
		acessory = {};
	};
	[53] = {
		name = "SMOKE GRENADE",
		alt_name = "Smoke Grenade",
		internal_name = "smokegrenade",
		category = "throwable",
		price = 300,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "smokegrenade.bmp",
		held_image = "smokegrenade.bmp",
		kill_image = "smokegrenade.bmp",
		display_image = "smokegrenade.bmp", 
		player_stance = "object",
		acessory = {};
	};
	[54] = {
		name = "FLARE",
		alt_name = "Flare",
		internal_name = "flare",
		category = "throwable",
		price = 150,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 1,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "flare.bmp",
		held_image = "flare.bmp",
		kill_image = "flare.bmp",
		display_image = "flare.bmp", 
		player_stance = "object",
		acessory = {};
	};
	[55] = {
		name = "BOMB",
		alt_name = "Bomb",
		internal_name = "bomb",
		category = "other",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 2150,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "bomb_d.bmp",
		held_image = "bomb.bmp",
		kill_image = "bomb.bmp",
		display_image = "bomb.bmp",
		player_stance = "melee",
		acessory = {};
	};
	[56] = {
		name = "DEFUSE KIT",
		alt_name = "Defuse Kit",
		internal_name = "defusekit",
		category = "equipment",
		price = 650,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0,
		common_path = "gfx/weapons/",
		dropped_image = "defusekit_d.bmp",
		held_image = "",
		kill_image = "",
		display_image = "defusekit_d.bmp",
		player_stance = "nothing",
		acessory = {};
	};
	[57] = {
		name = "KEVLAR",
		alt_name = "Kevlar",
		internal_name = "kevlar",
		category = "armor",
		price = 650,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "kevlar_d.bmp",
		held_image = "",
		kill_image = "",
		display_image = "kevlar_d.bmp",
		player_stance = "nothing",
		acessory = {};
	};
	[58] = {
		name = "KEVLAR+HELM",
		alt_name = "Kevlar + Helmet",
		internal_name = "kevlar+helm",
		category = "armor",
		price = 1000,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0,
		common_path = "gfx/weapons/",
		dropped_image = "kevlar+helm_d.bmp",
		held_image = "",
		kill_image = "",
		display_image = "kevlar+helm_d.bmp",
		player_stance = "nothing",
		acessory = {};
	};
	[59] = {
		name = "NIGHT VISION",
		alt_name = "Night Vision",
		internal_name = "nightvision",
		category = "equipment",
		price = 1250,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "nightvision.bmp",
		held_image = "nightvision.bmp",
		kill_image = "",
		display_image = "nightvision.bmp",
		player_stance = "nothing",
		acessory = {};
	};
	[60] = {
		name = "GAS MASK",
		alt_name = "Gas Mask",
		internal_name = "gasmask",
		category = "equipment",
		price = 250,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "gasmask.bmp",
		held_image = "gasmask.bmp",
		kill_image = "",
		display_image = "",
		player_stance = "nothing",
		acessory = {};
	};
	[61] = {
		name = "PRIMARY AMMO",
		alt_name = "Primary Ammo",
		internal_name = "primaryammo",
		category = "other",
		price = 50,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "primaryammo.bmp",
		held_image = "primaryammo.bmp",
		kill_image = "",
		display_image = "primaryammo.bmp",
		player_stance = "nothing",
		acessory = {};
	};
	[62] = {
		name = "SECONDARY AMMO",
		alt_name = "Secondary Ammo",
		internal_name = "secondaryammo",
		category = "other",
		price = 50,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "secondaryammo.bmp",
		held_image = "secondaryammo.bmp",
		kill_image = "",
		display_image = "secondaryammo.bmp",
		player_stance = "nothing",
		acessory = {};
	};
	[63] = {
		name = "PLANTED BOMB",
		alt_name = "Planted Bomb",
		internal_name = "secondaryammo",
		category = "other",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "bomb_d.bmp",
		held_image = "bomb.bmp",
		kill_image = "",
		display_image = "bomb.bmp",
		player_stance = "nothing",
		acessory = {};
	};
	[64] = {
		name = "MEDIKIT",
		alt_name = "Medikit",
		internal_name = "medikit",
		category = "other",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "medikit.bmp",
		held_image = "medikit.bmp",
		kill_image = "",
		display_image = "medikit.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[65] = {
		name = "BANDAGE",
		alt_name = "Bandage",
		internal_name = "bandage",
		category = "other",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "bandage.bmp",
		held_image = "bandage.bmp",
		kill_image = "",
		display_image = "bandage.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[66] = {
		name = "COINS",
		alt_name = "Coins",
		internal_name = "coins",
		category = "other",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "coins.bmp",
		held_image = "coins.bmp",
		kill_image = "coins.bmp",
		display_image = "coins.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[67] = {
		name = "MONEY",
		alt_name = "Money",
		internal_name = "money",
		category = "other",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "money_d.bmp",
		held_image = "money.bmp",
		kill_image = "money_k.bmp",
		display_image = "money_m.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[68] = {
		name = "GOLD",
		alt_name = "Gold",
		internal_name = "gold",
		category = "other",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "gold.bmp",
		held_image = "gold.bmp",
		kill_image = "",
		display_image = "gold.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[69] = {
		name = "MACHETE",
		alt_name = "Machete",
		internal_name = "machete",
		category = "melee",
		price = 0,
		damage = 175,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 14,
		range = 12,
		weight = 300,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "machete.bmp",
		held_image = "machete.bmp",
		kill_image = "machete_k.bmp",
		display_image = "machete.bmp", 
		player_stance = "melee",
		acessory = {};
	};
	[70] = {
		name = "RED FLAG",
		alt_name = "Red Flag",
		internal_name = "redflag",
		category = "equipment",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "redflag.bmp",
		held_image = "redflag.bmp",
		kill_image = "redflag.bmp",
		display_image = "redflag.bmp",
		player_stance = "nothing",
		acessory = {};
		flip = true;
		scale = 0.8;
		offset = -10;
	};
	[71] = {
		name = "BLUE FLAG",
		alt_name = "Blue Flag",
		internal_name = "blueflag",
		category = "equipment",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "blueflag.bmp",
		held_image = "blueflag.bmp",
		kill_image = "blueflag.bmp",
		display_image = "blueflag.bmp", 
		player_stance = "nothing",
		acessory = {};
		flip = true;
		scale = 0.8;
		offset = -10;
	};
	[72] = {
		name = "GAS GRENADE",
		alt_name = "Gas Grenade",
		internal_name = "gasgrenade",
		category = "throwable",
		price = 300,
		damage = 9,
		ammo_cap = 0,
		ammo_mag = 1,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "gasgrenade.bmp",
		held_image = "gasgrenade.bmp",
		kill_image = "gasgrenade_k.bmp",
		display_image = "gasgrenade.bmp",
		player_stance = "object",
		acessory = {};
	};
	[73] = {
		name = "MOLOTOV COCKTAIL",
		alt_name = "Molotov Cocktail",
		internal_name = "molotovcocktail",
		category = "throwable",
		price = 300,
		damage = 4,
		ammo_cap = 0,
		ammo_mag = 1,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "molotovcocktail.bmp",
		held_image = "molotovcocktail.bmp",
		kill_image = "molotovcocktail_k.bmp",
		display_image = "molotovcocktail.bmp", 
		player_stance = "object",
		acessory = {};
	};
	[74] = {
		name = "WRENCH",
		alt_name = "Wrench",
		internal_name = "wrench",
		category = "melee",
		price = 0,
		damage = 30,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 10,
		range = 7,
		weight = 150,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "wrench.bmp",
		held_image = "wrench.bmp",
		kill_image = "wrench_k.bmp",
		display_image = "wrench.bmp", 
		player_stance = "melee",
		acessory = {};
	};
	[75] = {
		name = "SNOWBALL",
		alt_name = "Snowball",
		internal_name = "snowball",
		category = "throwable",
		price = 50,
		damage = 35,
		ammo_cap = 0,
		ammo_mag = 10,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "snowball.bmp",
		held_image = "snowball.bmp",
		kill_image = "snowball_k.bmp",
		display_image = "snowball.bmp",
		player_stance = "object",
		acessory = {};
	};
	[76] = {
		name = "AIR STRIKE",
		alt_name = "Air Strike",
		internal_name = "airstrike",
		category = "throwable",
		price = 500,
		damage = 1500,
		ammo_cap = 0,
		ammo_mag = 1,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "airstrike.bmp",
		held_image = "airstrike.bmp",
		kill_image = "airstrike_k.bmp",
		display_image = "airstrike.bmp",
		player_stance = "object",
		acessory = {};
	};
	[77] = {
		name = "MINE",
		alt_name = "Mine",
		internal_name = "mine",
		category = "other",
		price = 400,
		damage = 150,
		ammo_cap = 0,
		ammo_mag = 3,
		rate_of_fire = 10,
		range = 120,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "mine.bmp",
		held_image = "mine.bmp",
		kill_image = "mine_k.bmp",
		display_image = "mine.bmp", 
		player_stance = "melee",
		acessory = {};
	};
	[78] = {
		name = "CLAW",
		alt_name = "Claw",
		internal_name = "claw",
		category = "melee",
		price = 0,
		damage = 50,
		damage_z1 = 90,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 12,
		range = 9,
		weight = 300,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "claw_d.bmp",
		held_image = "",
		kill_image = "claw_k.bmp",
		display_image = "",
		player_stance = "zombie",
		acessory = {};
	};
	[79] = {
		name = "LIGHT ARMOR",
		alt_name = "Light Armor 25%",
		internal_name = "lightarmor",
		category = "armor",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "lightarmor_d.bmp",
		held_image = "lightarmor.bmp",
		kill_image = "lightarmor_k.bmp",
		display_image = "lightarmor_m.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[80] = {
		name = "ARMOR",
		alt_name = "Armor 50%",
		internal_name = "armor",
		category = "armor",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "armor_d.bmp",
		held_image = "armor.bmp",
		kill_image = "armor_k.bmp",
		display_image = "armor_m.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[81] = {
		name = "HEAVY ARMOR",
		alt_name = "Heavy Armor 75%",
		internal_name = "heavyarmor",
		category = "armor",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "heavyarmor_d.bmp",
		held_image = "heavyarmor.bmp",
		kill_image = "heavyarmor_k.bmp",
		display_image = "heavyarmor_m.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[82] = {
		name = "MEDIC ARMOR",
		alt_name = "Medic Armor 50% + Regeneration",
		internal_name = "medicarmor",
		category = "armor",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "medicarmor_d.bmp",
		held_image = "medicarmor.bmp",
		kill_image = "medicarmor_k.bmp",
		display_image = "medicarmor_m.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[83] = {
		name = "SUPER ARMOR",
		alt_name = "Super Armor 95%",
		internal_name = "superarmor",
		category = "armor",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "superarmor_d.bmp",
		held_image = "superarmor.bmp",
		kill_image = "",
		display_image = "superarmor_d.bmp", 
		player_stance = "nothing",
		acessory = {};
	};
	[84] = {
		name = "STEALTH SUIT",
		alt_name = "Stealth Suit 0% + Invisibility",
		internal_name = "stealthsuit",
		category = "armor",
		price = 0,
		damage = 0,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 0,
		range = 0,
		weight = 0,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "stealthsuit_d.bmp",
		held_image = "",
		kill_image = "",
		display_image = "stealthsuit_d.bmp",
		player_stance = "nothing",
		opacity = 0.2,
		acessory = {};
	};
	[85] = {
		name = "CHAINSAW",
		alt_name = "Chainsaw",
		internal_name = "chainsaw",
		category = "melee",
		price = 0,
		damage = 60,
		ammo_cap = 0,
		ammo_mag = 0,
		rate_of_fire = 3,
		range = 12,
		weight = 2000,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "chainsaw_d.bmp",
		held_image = "chainsaw.bmp",
		kill_image = "chainsaw_k.bmp",
		display_image = "chainsaw_m.bmp",
		player_stance = "melee",
		acessory = {};
	};
	[86] = {
		name = "GUT BOMB",
		alt_name = "Gut Bomb",
		internal_name = "gutbomb",
		category = "throwable",
		price = 150,
		damage = 50,
		ammo_cap = 0,
		ammo_mag = 1,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "gutbomb.bmp",
		held_image = "gutbomb.bmp",
		kill_image = "gutbomb_k.bmp",
		display_image = "gutbomb.bmp", 
		player_stance = "object",
		acessory = {};
	};
	[87] = {
		name = "LASER MINE",
		alt_name = "Laser Mine",
		internal_name = "lasermine",
		category = "other",
		price = 400,
		damage = 150,
		ammo_cap = 0,
		ammo_mag = 3,
		rate_of_fire = 10,
		range = 200,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "lasermine.bmp",
		held_image = "lasermine.bmp",
		kill_image = "lasermine_k.bmp",
		display_image = "lasermine.bmp",
		player_stance = "object",
		acessory = {};
	};
	[88] = {
		name = "PORTAL GUN",
		alt_name = "Portal Gun",
		internal_name = "portalgun",
		category = "primary",
		price = 10000,
		damage = 0,
		ammo_cap = -1,
		ammo_mag = 0,
		rate_of_fire = 5,
		range = 300,
		weight = 3000,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "portalgun_d.bmp",
		held_image = "portalgun.bmp",
		kill_image = "portalgun_k.bmp",
		display_image = "portalgun_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[89] = {
		name = "SATCHEL CHARGE",
		alt_name = "Satchel Charge",
		internal_name = "satchelcharge",
		category = "throwable",
		price = 300,
		damage = 100,
		ammo_cap = 0,
		ammo_mag = 5,
		rate_of_fire = 10,
		range = 320,
		weight = 400,
		accuracy = 0, 
		common_path = "gfx/weapons/",
		dropped_image = "satchelcharge.bmp",
		held_image = "satchelcharge.bmp",
		kill_image = "satchelcharge_k.bmp",
		display_image = "satchelcharge.bmp", 
		player_stance = "object",
		acessory = {};
	};
	[90] = {
		name = "M134",
		alt_name = "M134",
		internal_name = "m134",
		category = "primary",
		price = 8100,
		damage = 13,
		ammo_cap = 800,
		ammo_mag = 200,
		rate_of_fire = 2,
		range = 300,
		weight = 39000, --You can make it even half less but m134 mass is 39KG irl
		accuracy = 50, 
		common_path = "gfx/weapons/",
		dropped_image = "m134_d.bmp",
		held_image = "m134.bmp",
		kill_image = "m134_k.bmp",
		display_image = "m134_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
	[91] = {
		name = "FN F2000",
		alt_name = "FN Herstal F2000",
		internal_name = "fnf2000",
		category = "primary",
		price = 3500,
		damage = 26,
		ammo_cap = 90,
		ammo_mag = 30,
		rate_of_fire = 3,
		range = 300,
		weight = 3600,
		accuracy = 80, 
		common_path = "gfx/weapons/",
		dropped_image = "fnf2000_d.bmp",
		held_image = "fnf2000.bmp",
		kill_image = "fnf2000_k.bmp",
		display_image = "fnf2000_m.bmp", 
		player_stance = "rifle",
		acessory = {};
	};
}

enum.itemdata_default = {
	name = "Default Object",
	alt_name = "Default Object",
	internal_name = "default",
	category = "other",
	price = 0,
	damage = 0,
	ammo_cap = 0,
	ammo_mag = 0,
	rate_of_fire = 0,
	range = 0,
	weight = 0,
	accuracy = 0, 
	common_path = "gfx/weapons/",
	dropped_image = "",
	held_image = "",
	display_image = "",
	kill_image = "",
	player_stance = "object",
	acessory = {};
}

enum.itemlist_meta = {
	__index = function(t, k)
		return enum.itemdata_default
	end
}
setmetatable(enum.itemlist, enum.itemdata_meta)

enum.itemlist_slots = {
	primary = 1,
	secondary = 2,
	melee = 3,
	throwable = 4,
	other = 5,
}

enum.npc = {
	[1] = {"Zombie", 150}, -- Zombie
	[2] = {"Headcrab", 30},  -- Headcrab
	[3] = {"Snark", 20},  -- Snark
	[4] = {"Vortigaunt", 200}, -- Vortigaunt
	[5] = {"Soldier", 100}, -- Soldier
}

enum.player = {
	ct1 = {
		path = "gfx/player/ct1.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	ct2 = {
		path = "gfx/player/ct2.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	ct3 = {
		path = "gfx/player/ct3.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	ct4 = {
		path = "gfx/player/ct4.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	t1 = {
		path = "gfx/player/t1.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	t2 = {
		path = "gfx/player/t2.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	t3 = {
		path = "gfx/player/t3.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	t4 = {
		path = "gfx/player/t4.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	vip = {
		path = "gfx/player/vip.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
	zombie = {
		path = "gfx/npc/zombie.bmp",
		stance = {
			handgun = {32, 32, 32, 32};
			rifle = {32, 64, 32, 32};
			melee = {32, 0, 32, 32};
			object = {32, 0, 32, 32};
			zombie = {0, 32, 32, 32};
			nothing = {0, 0, 32, 32};
		};
	};
}


enum.ui = {
	"gfx/splash.bmp",
	"gfx/pointer.bmp",
	"gfx/gui_icons.bmp",
	"gfx/gui_server.bmp",
	"gfx/hud_nums.bmp",
}

return enum