WRENCH_ONLY = false
LOCK_TEAM_CHANGE = false
ZM_BOT_T = false

parse('sv_gamemode 1')
parse('mp_antispeeder 0')
parse('mp_wpndmg "Machete" 100')
parse('mp_wpndmg "Claw" 35')
parse('mp_wpndmg "Flamethrower" 20')
parse('mp_wpndmg "Grenade Launcher" 75')
parse('mp_wpndmg "Rocket Launcher" 60')
parse('mp_wpndmg "Gut Bomb" 75')
parse('mp_wpndmg "AWP" 50')
parse('mp_wpndmg_z1 "AWP" 100')
parse('mp_wpndmg_z2 "AWP" 150')
parse('mp_wpndmg "Scout" 35')
parse('mp_wpndmg_z1 "Scout" 85')
parse('mp_wpndmg_z2 "Scout" 120')
parse('mp_wpndmg "MP5" 10')
parse('mp_wpndmg "TMP" 18')
parse('mp_wpndmg "P90" 20')
parse('mp_wpndmg "Mac 10" 12')
parse('mp_wpndmg "UMP45" 13')
parse('mp_wpndmg "Galil" 15')
parse('mp_wpndmg "Famas" 18')
parse('mp_wpndmg "AK-47" 22')
parse('mp_wpndmg "M4A1" 24')
parse('mp_wpndmg "SG552" 23')
parse('mp_wpndmg "Aug" 25')
parse('mp_wpndmg "G3SG1" 30')
parse('mp_wpndmg "SG550" 32')
parse('mp_wpndmg "M249" 19')
parse('mp_wpndmg "Laser" 75')

--parse('mp_respawndelay 2')
parse('mp_damagefactor 1')
parse('mp_weaponfadeout 10')
--parse('mp_infammo 1')
parse('mp_randomspawn 1')
parse('sv_usgnonly 0')
parse('sv_fow 0')
parse('sv_voicechat 0')

parse('mp_hud 75')

parse('mp_teamkillpenalty 0')
parse('mp_idlekick 0')

parse('mp_dispenser_money 0') 
parse('mp_dmspawnmoney 0') 
parse('mp_killbuildingmoney 0') 
parse('mp_deathdrop 4')
parse('mp_killteambuildings 1')
parse('mp_building_health "Barbed Wire" 40')
--[[
parse('mp_building_price "Barbed Wire" 0')
parse('mp_building_price "Dispenser" 0')
parse('mp_building_price "Barricade" 0')
parse('mp_building_price "Wall I" 0')
parse('mp_building_price "Wall II" 0')
parse('mp_building_price "Wall III" 0')
parse('mp_building_price "Turret" 0')
parse('mp_building_price "Teleporter Entrance" 0')
parse('mp_building_price "Teleporter Exit" 0')
parse('mp_building_price "Gate Field" 0')
parse('mp_building_price "Supply" 0')
--]]
