WRENCH_ONLY = false
LOCK_TEAM_CHANGE = false
ZM_BOT_T = false

parse('mp_antispeeder 0')
parse("mp_respawndelay 0")
parse("mp_infammo 0")
parse('mp_damagefactor 1')
parse('mp_weaponfadeout 10')
parse('sv_usgnonly 0')
parse('sv_fow 0')
parse('sv_voicechat 0')
parse('mp_hud 75')
parse('mp_teamkillpenalty 0')
parse('mp_idlekick 0')
parse('mp_dispenser_money 0') 
parse('mp_dmspawnmoney 0') 
parse('mp_killbuildingmoney 0') 
parse('mp_deathdrop 4')
parse('mp_killteambuildings 1')
parse('mp_building_health "Barbed Wire" 40')

if map("name")=="fun_classmod_ctf" then
	parse("sv_gamemode 2")
	parse("mp_randomspawn 0")
elseif map("name")=="fun_classmod_arena" then
	parse("sv_gamemode 1")
	parse("mp_randomspawn 1")
elseif map("name")=="fun_classmod2" then
	parse("sv_gamemode 1")
	parse("mp_randomspawn 1")	
end

parse('mp_wpndmg "USP" 10')
parse('mp_wpndmg "Glock" 10')
parse('mp_wpndmg "Elite" 10')
parse('mp_wpndmg "Five-Seven" 10')
parse('mp_wpndmg "Deagle" 50')
parse('mp_wpndmg "P228" 10') -- Medic		
parse('mp_wpndmg "Tesla Coil" 2')
parse('mp_wpndmg "Knife" 10')
parse('mp_wpndmg "Machete" 100')
parse('mp_wpndmg "Claw" 35')
parse('mp_wpndmg "Flamethrower" 10')
parse('mp_wpndmg "Grenade Launcher" 75')
parse('mp_wpndmg "Rocket Launcher" 60')
parse('mp_wpndmg "RPG Launcher" 120')
parse('mp_wpndmg "Gut Bomb" 75')
parse('mp_wpndmg "AWP" 50')
parse('mp_wpndmg_z1 "AWP" 100')
parse('mp_wpndmg_z2 "AWP" 150')
parse('mp_wpndmg "Scout" 35')
parse('mp_wpndmg_z1 "Scout" 85')
parse('mp_wpndmg_z2 "Scout" 120')
parse('mp_wpndmg "MP5" 6')
parse('mp_wpndmg "TMP" 7')
parse('mp_wpndmg "P90" 8')
parse('mp_wpndmg "Mac 10" 6')
parse('mp_wpndmg "UMP45" 6')
parse('mp_wpndmg "Galil" 6')
parse('mp_wpndmg "Famas" 8')
parse('mp_wpndmg "AK-47" 10')
parse('mp_wpndmg "M4A1" 10')
parse('mp_wpndmg "SG552" 12')
parse('mp_wpndmg "Aug" 10')
parse('mp_wpndmg "G3SG1" 20')
parse('mp_wpndmg "SG550" 20')
parse('mp_wpndmg "M249" 5')
parse('mp_wpndmg "Laser" 75')
parse('mp_wpndmg "m134" 8')
parse('mp_weaponfadeout 5')
parse('bot_add_t')
--

--[[
parse('mp_building_price "Barbed Wire" 0')
parse('mp_building_price "Dispenser" 0')
parse('mp_building_price "Barricade" 0')
parse('mp_building_price "Wall I" 0')
parse('mp_building_price "Wall II" 0')
parse('mp_building_price "Wall III" 0')
parse('mp_building_price "Turret" 0')
parse('mp_building_price "Teleporter Entrance" 0')
parse('mp_building_price "Teleporter Exit" 0')
parse('mp_building_price "Gate Field" 0')
parse('mp_building_price "Supply" 0')
--]]
