parse("sv_gamemode 1")
parse("mp_randomspawn 0")
parse("mp_radar 0")
parse("mp_hud 64")
--parse("bot_add_t")
--parse("bot_add_ct")
parse("bot_freeze 0")
parse("sv_forcelight 1")
parse("mp_deathdrop 0")
parse("mp_infammo 1")
parse("mp_supply_items 51,23,39,1,2,34,67,30,32")
parse("mp_weaponfadeout 60")
parse("sv_daylighttime 230")
timer(1000,"parse","mp_randomspawn 0")